---
kind: pipeline
type: kubernetes
name: default

steps:
- name: build & push docker image (main branch)
  image: plugins/docker
  when:
    branch:
    - main
    event:
      exclude:
        - tag
  settings:
    username: drone
    password:
      from_secret: cr_password
    registry: cr.grechka.family
    repo: cr.grechka.family/socat
    auto_tag: true
    force_tag: true
- name: build & push docker image (tag)
  image: plugins/docker
  when:
    event:
    - tag
  settings:
    username: drone
    password:
      from_secret: cr_password
    registry: cr.grechka.family
    repo: cr.grechka.family/socat
    auto_tag: true
    force_tag: true